* Les FAQs des administrations publiques

Ce dépôt contient un programme permettant de collecter les questions
et les réponses proposées, dans le cadre de l'épidémie de Covid-19,
par ces organismes publiques :

- URSSAF
- Pôle Emploi
- gouvernement.fr
- education.gouv.fr
- associations.gouv.fr
- travail-emploi.gouv.fr
- handicap.gouv.fr
- etudiant.gouv.fr
- solidarites-sante.gouv.fr
- sfpt-fr.org
- defense.gouv.fr
- economie.gouv.fr
- service-public.fr

Vous pouvez consulter les questions/réponses sur
[[https://www.covid19-faq.fr]].

* Voir les questions et les réponses

Les questions sont disponibles dans [[https://bzg.github.io/covid19-faq-data/faq-questions.json][ce fichier json]].

Chaque question contient la question (=q=), un identifiant (=i=) et une
source (=s=).

Chaque réponse est disponible sous forme de fichier =json= dont le nom
reprend l'identifiant de la question.  Par exemple, pour la première
question de =faq-questions.json=, la réponse est [[https://bzg.github.io/covid19-faq-data/answers/d8ff9d6391283221b4dfe1f36f95fc22.json][ici]].

Chaque réponse contient la question (=q=), la réponse (=r=), l'identifiant
(=i=), la source (=s=), l'URL (=u=), la date de collecte (=m=).

* Contribuer

Votre aide est la bienvenue.  Vous pouvez contribuer en ouvrant une
issue pour proposer une nouvelle source d'information ou en signalant
un problème avec une ou plusieurs questions/réponses.

* Soutenir l'écosystème Clojure(script)

Si vous aimez Clojure(script), vous pouvez soutenir son écosystème en
faisant un don à [[https://www.clojuriststogether.org][clojuriststogether.org]].

* Licence

2020 Bastien Guerry.

Le code source de ce dépôt est publiée sous licence [[file:LICENSE][EPL 2.0]].
